# Copyright (C) 2021  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier:ISC

name: fpga-interchange
channels:
    - defaults
    - litex-hub
dependencies:
    - litex-hub::capnproto-java=0.1.5_0012_g44a8c1e=20201104_165332
    - litex-hub::gcc-riscv64-elf-newlib=9.2.0=20201119_154229
    - litex-hub::iverilog=0_8_5850_g540555fc=20210730_085634
    - litex-hub::nextpnr-fpga_interchange=0.1_103_g74c99f91=20220202_022309_py37
    - litex-hub::prjoxide=v0.0_398_g711770c=20210730_085634
    - litex-hub::prjxray-db=0.0_257_g0a0adde=20220202_022309
    - litex-hub::prjxray-tools=0.1_2942_g5349556b=20220202_022309
    - litex-hub::vtr-optimized=8.0.0_5170_g81b5aa2a8=20220202_022309
    - litex-hub::yosys=0.13_39_g958c3a46a=20220202_022309_py37
    - swig
    - pip
    - pip:
        - -r requirements.txt
